[global]
config_version=2
backend=TensorRT
logging=yes
[slot_1]
profile_name=Test Performance
chain_1_min_resolution=1280x720
chain_1_max_resolution=1920x1080
chain_1_max_fps=31
chain_1_model_1_name=2x_AnimeJaNai_HD_V3_Performance_SPANF3_b5f48_unshuffle_fp16
chain_2_max_resolution=1280x720
chain_2_max_fps=31
chain_2_model_1_name=2x_AnimeJaNai_HD_V3_Performance_SPANF3_b5f48_unshuffle_fp16
[slot_2]
profile_name=Test Balanced
chain_1_max_fps=61
chain_1_model_1_name=2x_AnimeJaNai_HD_V3_Balanced_SPANF3_b8f64_unshuffle_fp16
